name: Reusable Build and Push to ECR Template

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      app-color:
        required: true
        type: string
    outputs:
      imagen-generada:
        value: ${{ jobs.build-and-push-ecr.outputs.full-uri }}
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest
    outputs:
      full-uri: ${{ steps.build-image.outputs.uri }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.aws-region }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr-repository }}
          IMAGE_TAG: ${{ inputs.image-tag }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker build --build-arg BUILD_COLOR=${{ inputs.app-color }} -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "uri=$IMAGE_URI" >> $GITHUB_OUTPUT
