name: Reusable Deploy to ECS Template

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      ecs-cluster:
        required: true
        type: string
      ecs-service:
        required: true
        type: string
      task-definition-family:
        required: true
        type: string
      container-name:
        required: true
        type: string
      image-uri:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false

jobs:
  deploy-ecs:
    runs-on: ubuntu-latest
    steps:
      # 1. Autenticación en AWS
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.aws-region }}

      # 2. Descargar la definición de tarea actual (evita tener que quemarla en el código)
      - name: Descargar Task Definition actual
        run: aws ecs describe-task-definition --task-definition ${{ inputs.task-definition-family }} --query taskDefinition > task-definition.json

      # 3. Actualizar la definición con la nueva imagen de ECR
      - name: Renderizar nueva Task Definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ inputs.container-name }}
          image: ${{ inputs.image-uri }}

      # 4. Desplegar en el clúster
      - name: Desplegar en Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ inputs.ecs-service }}
          cluster: ${{ inputs.ecs-cluster }}
          wait-for-service-stability: true
