name: TechMarket Main CI/CD Pipeline (AWS ECR Version)

on:
  push:
    branches:
      - main

jobs:
  # -------------------------------------------------------------
  # 1. FASE DE CONSTRUCCIÓN (Subiendo a ECR)
  # -------------------------------------------------------------
  build_phase:
    name: Fase de Construcción
    uses: ./.github/workflows/templates/template_build.yml
    with:
      aws-region: 'us-east-1'
      ecr-repository: 'techmarket-repo'
      image-tag: 'v1.0.0'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  # -------------------------------------------------------------
  # 2. FASE DE PRUEBAS
  # -------------------------------------------------------------
  test_phase:
    name: Fase de Pruebas de Seguridad
    needs: build_phase
    uses: ./.github/workflows/templates/template_test.yml
    with:
      image-to-scan: '${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/techmarket-repo:v1.0.0'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  # -------------------------------------------------------------
  # 3. FASE DE DESPLIEGUE (ENTORNO DESARROLLO)
  # -------------------------------------------------------------
  deploy_dev_phase:
    name: Fase de Despliegue (Dev)
    needs: test_phase
    uses: ./.github/workflows/templates/template_deploy.yml
    with:
      environment: 'dev'
      aws-region: 'us-east-1'
      ecr-repository: 'techmarket-repo'
      image-tag: 'v1.0.0'
      app-port: '8080'
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      ECR_REGISTRY: '${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com'
